# Generated by Django 3.2.5 on 2022-02-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourdatabase', '0002_auto_20211230_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osrimolecule',
            name='image',
        ),
    ]
