# Generated by Django 3.2.5 on 2021-11-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemblbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wntmolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.FileField(upload_to='image/inhouse')),
            ],
        ),
    ]
