# Generated by Django 3.2.5 on 2021-11-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemblbase', '0002_wntmolecule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wntmolecule',
            name='imgfile',
            field=models.FileField(upload_to='image/thanks'),
        ),
    ]
