# Generated by Django 3.2.5 on 2021-11-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemblbase', '0003_alter_wntmolecule_imgfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='thankspic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.FileField(upload_to='image/thanks')),
            ],
        ),
    ]
