#chemprop_train --data_path data/train_random_nocanonical.csv --dataset_type classification --save_dir checkpoints_22 --config_path hyperoptfile --epochs 100  --separate_test_path data/test_random_nocanonical.csv --separate_val_path data/val_none.csv --features_generator rdkit_2d_normalized --no_features_scaling --aggregation_norm 100
#chemprop_train --data_path data/train_random_nocanonical.csv --dataset_type classification --save_dir checkpoints_23 --config_path hyperoptfile --epochs 100  --separate_test_path data/test_random_nocanonical.csv --split_sizes 0.9 0.1 0.0 --features_generator rdkit_2d_normalized --no_features_scaling --aggregation_norm 100
#chemprop_train --data_path data/train_full.csv --dataset_type classification --save_dir checkpoints_24 --config_path hyperoptfile3 --epochs 100 --separate_test_path data/test_random_nocanonical.csv --separate_val_path data/val_full.csv --features_generator rdkit_2d_normalized --no_features_scaling
#chemprop_train --data_path data/train_full.csv --dataset_type classification --save_dir checkpoints_25 --config_path hyperoptfile3 --epochs 100 --separate_test_path data/test_random_nocanonical.csv --separate_val_path data/val_full.csv --features_generator rdkit_2d_normalized --no_features_scaling
#chemprop_train --data_path data/train_full.csv --dataset_type classification --save_dir checkpoints_26 --config_path hyperoptfile3 --epochs 100 --separate_test_path data/test_random_nocanonical.csv --separate_val_path data/val_full.csv --features_generator rdkit_2d_normalized --no_features_scaling
#chemprop_train --data_path data/train_full.csv --dataset_type classification --save_dir checkpoints_27 --config_path hyperoptfile3 --epochs 100 --separate_test_path data/test_random_nocanonical.csv --separate_val_path data/val_full.csv --features_generator rdkit_2d_normalized --no_features_scaling
#chemprop_train --data_path data/train_full.csv --dataset_type classification --save_dir checkpoints_28 --config_path hyperoptfile3 --epochs 100 --separate_test_path data/test_random_nocanonical.csv --separate_val_path data/val_full.csv --features_generator rdkit_2d_normalized --no_features_scaling
#chemprop_train --data_path data/train_full.csv --dataset_type classification --save_dir checkpoints_29 --config_path hyperoptfile3 --epochs 100 --separate_test_path data/test_random_nocanonical.csv --separate_val_path data/val_full.csv --features_generator rdkit_2d_normalized --no_features_scaling
#chemprop_train --data_path data/train_full.csv --dataset_type classification --save_dir checkpoints_30 --config_path hyperoptfile3 --epochs 100 --separate_test_path data/test_random_nocanonical.csv --separate_val_path data/val_full.csv --features_generator rdkit_2d_normalized --no_features_scaling
#chemprop_train --data_path data/train_full.csv --dataset_type classification --save_dir checkpoints_31 --config_path hyperoptfile3 --epochs 100 --separate_test_path data/test_random_nocanonical.csv --separate_val_path data/val_full.csv --features_generator rdkit_2d_normalized --no_features_scaling
#chemprop_train --data_path data/train_full.csv --dataset_type classification --save_dir checkpoints_32 --config_path hyperoptfile3 --epochs 100 --separate_test_path data/test_random_nocanonical.csv --separate_val_path data/val_full.csv --features_generator rdkit_2d_normalized --no_features_scaling
#chemprop_train --data_path data/train_full.csv --dataset_type classification --save_dir checkpoints_33 --config_path hyperoptfile3 --epochs 100 --separate_test_path data/test_random_nocanonical.csv --separate_val_path data/val_full.csv --features_generator rdkit_2d_normalized --no_features_scaling
#chemprop_train --data_path data/train_full.csv --dataset_type classification --save_dir checkpoints_34 --config_path hyperoptfile3 --epochs 100 --separate_test_path data/test2_random_nocanonical.csv --separate_val_path data/val_full.csv --features_generator rdkit_2d_normalized --no_features_scaling
#chemprop_train --data_path data/train_full.csv --dataset_type classification --save_dir checkpoints_35 --config_path hyperoptfile5 --epochs 100 --separate_test_path data/test_random_nocanonical.csv --separate_val_path data/val_full.csv --features_generator rdkit_2d_normalized --no_features_scaling
chemprop_train --data_path data/train_full.csv --dataset_type classification --save_dir checkpoints_36 --config_path hyperoptfile5 --epochs 100 --separate_test_path data/test_random_nocanonical.csv --separate_val_path data/val_full.csv --features_generator rdkit_2d_normalized --no_features_scaling
