# Generated by Django 3.2.5 on 2022-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbdd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_file', models.FileField(upload_to='')),
                ('error_file', models.FileField(upload_to='')),
            ],
        ),
    ]
